### ISSUE TITLE
Automate PHP lib publishing

### ISSUE THREAD

**Issue by pearsonhenri** [legiti/inspetor-php#16]
**BLOCKED**
- https://github.com/inspetor/inspetor-php/issues/29

**BLOCKS**
- Client integration

Use GitHub's built-in webhook functionality to automatically publish new releases of the repository to Packagist (via steps listed here: https://kevingoedecke.me/2018/08/24/update-packagist-with-github-webhooks-without-service/)

Some additional required steps:
- [x] Create an Inspetor Packagist account (instead of using Theo's personal email)
- [ ] Fix GitHub webhook definition
- [x] Delete existing tags (not sure if we actually want/need to)
- [x] Standardize publication branching workflow (@pearsonhenri and @theosato)
- [x] Write a script to automatically run the publication branching workflow

**Comment by pearsonhenri** [comment]
@theosato I created a new Packagist account (username `inspetor`; password is on 1Pass)

**Comment by pearsonhenri** [comment]
@theosato do we want to/need to do any of the above-listed items?

**Comment by theosato** [comment]
> @theosato do we want to/need to do any of the above-listed items?

I suppose we don't need any script once the GitHub webhook should do the job, but we need to test. The other items were already covered.

**Comment by lbiselli** [comment]
We are not using this lib anymore
